language: python

python:
  - 3.6

services:
  - rabbitmq

install:
  - pip install -r requirements.txt
  - pip install pylint==2.3.1
  - pip install pytest-asyncio==0.10.0 pytest==5.0.1

script:
  - find -name "*.py" -not -path "./venv/*" | xargs pylint
  - env PYTHONPATH=$(pwd) py.test tests/
