language: python

python:
  - 3.6

services:
  - rabbitmq

install:
  - pip install -r requirements-dev.txt

script:
  - find -name "*.py" -not -path "./venv/*" | xargs pylint
  - env PYTHONPATH=$(pwd) py.test tests/
