dist: trusty

language: python

python:
  - 3.6

services:
  - rabbitmq

install:
  - pip install -r requirements-dev.txt

script:
  - flake8
  - cd tests/ && flake8 && cd ../
  - py.test --cov --cov-config=setup.cfg

after_success:
  - codecov
