language: python

python:
  - 3.6

services:
  - rabbitmq

install:
  - pip install -r requirements-dev.txt

script:
  - find -name "*.py" -not -path "./venv/*" | xargs pylint
  - py.test --cov --cov-config=setup.cfg

after_success:
  - codecov
